from .roles import BY_ROLE
from .files import safe_file
TEMPLATES={
'developer':('generated_feature.py','Developer created a starter implementation.'),'tester':('qa_report.md','QA report with happy-path, validation, boundary, regression and security checks.'),'ui_ux':('ui_ux_spec.md','Responsive UI/UX specification and component plan.'),'database':('database_design.md','Database entities, relationships, indexes and integrity plan.'),'devops':('deployment_plan.md','Render/Docker deployment and rollback plan.'),'security':('security_report.md','OWASP-oriented security review and remediation checklist.'),'ml_engineer':('ml_plan.md','Dataset, baseline model, evaluation and inference plan.'),'data_entry':('records.csv','field,value\nstatus,captured\n'),'hr':('hr_workflow.md','Candidate screening and interview workflow.'),'email':('email_draft.txt','Draft prepared. External sending requires approval.'),'documentation':('README_generated.md','Generated technical documentation.'),'project_manager':('project_plan.md','Milestones, owners, dependencies and progress plan.'),'product_manager':('product_requirements.md','User stories, backlog priorities and acceptance criteria.'),'code_reviewer':('code_review.md','Readability, architecture, error handling and maintainability review.'),'researcher':('research_report.md','Research plan and findings structure.'),'data_analyst':('data_analysis.md','KPI and trend analysis plan.'),'sales':('sales_plan.md','Lead qualification, proposal and follow-up workflow.'),'marketing':('marketing_plan.md','Audience, messaging, channel and campaign measurement plan.'),'support':('support_resolution.md','Issue reproduction, severity and resolution workflow.'),'finance':('finance_report.md','Budget, expense and anomaly review.'),'compliance':('compliance_report.md','Privacy, policy and regulatory checklist.'),'operations':('operations_plan.md','Workflow, bottleneck, SLA and coordination plan.'),'automation':('automation_plan.md','Safe automation workflow with approval gates.')}
def execute(task):
 role=task.assigned_role;meta=BY_ROLE.get(role,BY_ROLE['manager']);fname,summary=TEMPLATES.get(role,('manager_notes.md','Manager coordinated the work.'))
 p=safe_file('demo-company',fname);p.parent.mkdir(parents=True,exist_ok=True)
 content=f'# {meta["name"]} — {meta["title"]}\n\nTask: {task.title}\n\nRequirement: {task.description}\n\n{summary}\n'
 p.write_text(content,encoding='utf-8')
 approval=role in {'email'} or ('call' in task.description.lower()) or ('send' in task.description.lower() and role in {'hr','sales','marketing'})
 return str(p),summary,approval
