ROLES=[
 {'id':'manager','name':'Aarav','title':'AI Company Manager','icon':'🧠'},
 {'id':'project_manager','name':'Kabir','title':'Project Manager','icon':'📋'},
 {'id':'product_manager','name':'Ishaan','title':'Product Manager','icon':'🧭'},
 {'id':'developer','name':'Arjun','title':'Senior Developer','icon':'👨‍💻'},
 {'id':'code_reviewer','name':'Rohan','title':'Code Reviewer','icon':'🔍'},
 {'id':'tester','name':'Neha','title':'QA Tester','icon':'🧪'},
 {'id':'ui_ux','name':'Meera','title':'UI/UX Designer','icon':'🎨'},
 {'id':'database','name':'Dev','title':'Database Engineer','icon':'🗄️'},
 {'id':'devops','name':'Vihaan','title':'DevOps Engineer','icon':'🚀'},
 {'id':'security','name':'Aryan','title':'Security Analyst','icon':'🛡️'},
 {'id':'ml_engineer','name':'Aditi','title':'ML Engineer','icon':'🤖'},
 {'id':'automation','name':'Kunal','title':'Automation Engineer','icon':'⚙️'},
 {'id':'data_analyst','name':'Ananya','title':'Data Analyst','icon':'📈'},
 {'id':'data_entry','name':'Rahul','title':'Data Entry Executive','icon':'⌨️'},
 {'id':'researcher','name':'Tara','title':'Research Analyst','icon':'🔬'},
 {'id':'hr','name':'Priya','title':'HR Manager','icon':'👩‍💼'},
 {'id':'email','name':'Riya','title':'Email Assistant','icon':'📧'},
 {'id':'sales','name':'Vikram','title':'Sales Executive','icon':'💼'},
 {'id':'marketing','name':'Sara','title':'Marketing Specialist','icon':'📣'},
 {'id':'support','name':'Nisha','title':'Customer Support','icon':'🎧'},
 {'id':'documentation','name':'Aditya','title':'Technical Writer','icon':'📚'},
 {'id':'finance','name':'Karan','title':'Finance Assistant','icon':'💰'},
 {'id':'compliance','name':'Simran','title':'Compliance Officer','icon':'⚖️'},
 {'id':'operations','name':'Om','title':'Operations Manager','icon':'🏢'},
]
BY_ROLE={r['id']:r for r in ROLES}; BY_NAME={r['name'].lower():r for r in ROLES}
